### ISSUE TITLE
Cmd.either broken when error happens

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-elmish#302]
Hi @MangelMaxime,

this change broke our either function:

![Image](https://github.com/user-attachments/assets/acbfea8f-5d2a-4a4f-91e5-ef56f3dc068b)

the try catch doesn't happen on the runtime of promise but only on the "creation of the promise". So when the promise actually runs and an error happens then it is a uncaught javascript exception and everything blows up. Could you please consider to readd the catch statements? 
Want me to send a PR?

Cheers

**Comment by MangelMaxime** [comment]
Hello @forki,

I think you have this problem because of a bug in async prior to Fable [5.0.0-alpha.11](https://github.com/fable-compiler/Fable/releases/tag/5.0.0-alpha.11).

Before that version, the exception inside of async were not propagated correctly. Could you please check if using the latest alpha version of Fable fix the issue ?

Because in theory we covered this cases here : https://github.com/elmish/elmish/blob/v4.x/tests/CmdTests.fs#L143-L185

**Comment by forki** [comment]
it will probably fix it, but I'm not really comfortable using an alpha version of fable in a large prod system.

For the time being we could do try catch and the .catch here both. If that's OK for you

**Comment by MangelMaxime** [comment]
I could back port the fix to Fable 4, would this work for you?

**Comment by forki** [comment]
yes absolutely. That would be fantastic

**Comment by MangelMaxime** [comment]
@forki Sorry took me sometime to make the release because of a bug with .NET 9 being available now...

This issue should be fixed in Fable 4.25.0

**Comment by forki** [comment]
unfortunately Fable 4.25 and Fable.Elmish 4.2 combo still have that issue

**Comment by MangelMaxime** [comment]
That's strange perhaps I didn't back-port the complete fixes 🤔

**Comment by MangelMaxime** [comment]
I was taking a look again at this issue, and I think it is "normal" that Fable 4.25.0 didn't fix the issue reported by @forki.

This is because 4.25.0 fixes the handling for `async` inside of Fable code, but the bug reported by @forki is related to `promise`. For the promises I believe we need to keep calling `catch` on them directly.

They behave differently from `async`
